### ISSUE TITLE
Add AWS SSL Certificate to Grayskull and support secure connections to Amazon RDS

### ISSUE THREAD

**Issue by danielgary** [gatewayapps/grayskull#153]
AWS SSL available here: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem

We should discuss the upside and downside of this:

- Communication over SSL is 👍
- We will have to update this whenever the certificate expires/is updated and the existing installations would also need to be updated
- This only covers AWS, does not handle Azure/Google Cloud/Custom

**Comment by johnmurphy01** [comment]
The certificate authority shouldn't change often. When the RDS instance was created, it defaulted to the 2015 authority. However as of March 2020, the 2015 authority will no longer be valid. 

What we could do is put the file in the grayskull project and give it some generic name. Then if/when the authority expires again, we just overwrite the existing `pem` file, that way we don't have to change the connection string

**Comment by danielgary** [comment]
Right, but existing deployments of Grayskull would have to change.  It essentially adds a time bomb

**Comment by johnmurphy01** [comment]
True, but AWS appears to give ample time to make the switch and we have a warning message in the Console regarding the certificate expiration.

**Comment by danielgary** [comment]
I would prefer to figure out a way to store the certificate contents in an environment variable or possibly provide a URL to the cert and download it at runtime...that adds some overhead though.
