### ISSUE TITLE
Stuck at /register page in development

### ISSUE THREAD

**Issue by NathanWaddell121107** [gatewayapps/grayskull#314]
I believe this only applies to development environments due to the fact that we don't interact with email servers in development.

Since we rely on "Email verification" to register a new user, we auto verify users in development mode which works as intended. (in the database, the users verified value is true)

However, after going through the user creation process, something is broken in the UI flow and still holds you back and tries to force you to verify using an email. (see screenshot attached below)

Everything works fine after you replace the URL and go back to the base URL `127.0.0.1/` at which point you are logged in, verified, and can access everything as expected.

![image](https://user-images.githubusercontent.com/45477581/131222751-36d7b0a5-c8fb-4bfc-aefc-e1d3bebe2c13.png)

**Comment by danielgary** [comment]
Suggested solution:

- [ ] Show a 15 second countdown
- [ ] At the end of the countdown, redirect to /login
- [ ] The countdown should read Redirecting to Login page in **n** seconds...
- [ ] Login page should be a link to /login
